name: Build Docker image and Push to Docker Hub
run-name: ${{ gitea.actor }} is building the app

on:
  push:
    branches: [master, test]
  pull_request:
    branches: [master]

jobs:
  构建:
    runs-on: ubuntu-latest
    container:
      image: purp1e/alpine-with-docker:latest
    steps:
      - name: 切换到当前分支
        uses: actions/checkout@v3

      # - name: 设置 QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: 构建和推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: purp1e/hlae-site:latest
          cache-from: type=registry,ref=user/app:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max
